- hosts: all
  vars: 
     middle: "{{m}}"
  tasks:
    - include_vars: "hostname.txt"
    - name: setting hostname
      hostname:
        name: "{{s}}{{m}}{{e}}"
      register: x
      sudo: yes
      ignore_errors: yes
      with_items: m
    - debug:
        msg: "{{x}}"

